# File: azure-pipelines\nightly-snapshot-releases\msal.yml
# Description: Publish msal release nightly to internal feed
# https://identitydivision.visualstudio.com/Engineering/_packaging?_a=feed&feed=AndroidADAL
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

parameters:
- name: productFlavors
  displayName: Product Flavor
  type: string
  default: Snapshot
  values:
  - Local
  - Dist
  - Snapshot
- name: signingConfigurations
  displayName: Signing Configuration
  type: string
  default: Debug
  values:
  - Debug
  - Release

resources:
 repositories:
 - repository: common
   type: github
   name: AzureAD/microsoft-authentication-library-common-for-android
   ref: pedroro/pipes
   endpoint: ANDROID_GITHUB

jobs:
- job: assemble_publish
  displayName: Assemble and publish
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - template: azure-pipelines/templates/steps/nightly-snapshot-releases/assemble-publish.yml@common
    parameters:
      versionVariant: Snapshot # Only option avalible
      assembleVariant: ${{ parameters.productFlavors }}${{ parameters.signingConfigurations }}
      testVariant: ${{ parameters.productFlavors }}${{ parameters.signingConfigurations}}UnitTest
      testArguments: -ProbolectricSdkVersion=28
      project: msal
      envVstsMvnAt: ENV_VSTS_MVN_ANDROID_MSAL_ACCESSTOKEN
      ${{ if eq(parameters.productFlavors, 'Local') }}:
        commmonBranch: ${{ variables.commonLocalBranch }}