# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'android:serverUrl' was defined in the Variables tab
# Variable 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable 'gcloud_project_id' was defined in the Variables tab
# Variable 'mvnAccessToken' was defined in the Variables tab
# Variable 'test_repo_branch' was defined in the Variables tab
# Variable 'test_repo_dir' was defined in the Variables tab
# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: 0 3 * * *
  branches:
    include:
    - dev
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: refs/heads/pedroro/IDDP-pipelines
    endpoint: ANDROID_GITHUB
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: azure-pipelines/templates/steps/credscan-policheck.yml@common
    parameters:
      policheckCmdLineArgsDir: adal
  - task: DownloadBuildArtifacts@0
    displayName: Download Broker Host APK
    inputs:
      buildType: specific
      project: a7934fdd-dcde-4492-a406-7fad6ac00e17
      definition: 1195
      buildVersionToDownload: latestFromBranch
      branchName: refs/heads/dev
      artifactName: BrokerHostDebug
  - task: DownloadSecureFile@1
    name: azureSampleApk
    displayName: Download Azure Sample Debug APK
    enabled: False
    inputs:
      secureFile: AzureSampleDebug.apk
      retryCount: 5
  - task: DownloadBuildArtifacts@0
    displayName: Download Azure Sample Local Debug
    inputs:
      buildType: specific
      project: a7934fdd-dcde-4492-a406-7fad6ac00e17
      definition: 1279
      artifactName: AzureSampleLocalDebug
  - template: azure-pipelines/templates/steps/ui-automation/gcloud.yml@common
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble MSAL Automation App
    inputs:
      tasks: clean msalautomationapp:assembleLocalBrokerHost -PlabSecret=$(AndroidAutomationRunnerAppSecret) -PpreferPreInstalledApks
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: Gradle@1
    displayName: Assemble MSAL Automation App Instrumented Tests
    inputs:
      tasks: msalautomationapp:assembleLocalBrokerHostDebugAndroidTest -PlabSecret=$(AndroidAutomationRunnerAppSecret) -PpreferPreInstalledApks
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: PowerShell@2
    displayName: Run UI Automation on Firebase
    inputs:
      targetType: inline
      script: >-
        $baseApkPath = "$(Build.SourcesDirectory)\msalautomationapp\build\outputs\apk"

        $appApk = "$baseApkPath\localBrokerHost\debug\msalautomationapp-local-BrokerHost-debug.apk"

        $testApk = "$baseApkPath\androidTest\localBrokerHost\debug\msalautomationapp-local-BrokerHost-debug-androidTest.apk"

        $brokerHostApk = "$(System.ArtifactsDirectory)\BrokerHostDebug\brokerHost-local-debug.apk"

        $azureSampleApk = "$(System.ArtifactsDirectory)\AzureSampleLocalDebug\AzureSample-local-debug.apk"

        $appApk

        $testApk

        $brokerHostApk

        $azureSampleApk

        gcloud firebase test android run --type instrumentation --app $appApk --test $testApk --device model=flame,version=29 --timeout 45m --additional-apks $brokerHostApk,$azureSampleApk --results-dir msal-BrokerHost-$(Build.BuildId)-$(Build.BuildNumber) --directories-to-pull "/sdcard" --use-orchestrator --environment-variables clearPackageData=true --results-history-name "MSAL dev w/ dev BrokerHost"
  - task: PowerShell@2
    displayName: Download Test Result File
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: gsutil cp gs://test-lab-ffz6x9pu2y62a-is0rq7a7rwdhi/msal-BrokerHost-$(Build.BuildId)-$(Build.BuildNumber)/flame-29-en-portrait/test_result_1.xml $(Build.SourcesDirectory)
  - task: PublishTestResults@2
    displayName: Publish Test Results to ADO
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '*test_result*.xml'
      searchFolder: $(Build.SourcesDirectory)
      testRunTitle: 'MSAL UI Automation - Build # $(Build.BuildNumber)'
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
