// Load credentials for VSTS Maven
project.ext.vstsUsername = System.getenv("ENV_VSTS_MVN_CRED_USERNAME") != null ? System.getenv("ENV_VSTS_MVN_CRED_USERNAME") : project.findProperty("vstsUsername")
project.ext.vstsMavenAccessToken = System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") != null ? System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") : project.findProperty("vstsMavenAccessToken")

buildscript {
    apply from: rootProject.file("gradle/versions.gradle")

    repositories {
        // If you don't have access to the package feed uncomment these repositories
        // mavenCentral()
        google()
        maven {
            // msazure and aria are consumed via upstream sources of the NewAndroid feed.
            name "vsts-maven-new-android"
            url "https://identitydivision.pkgs.visualstudio.com/_packaging/NewAndroid/maven/v1"
            credentials {
                username System.getenv("ENV_VSTS_MVN_CRED_USERNAME") != null ? System.getenv("ENV_VSTS_MVN_CRED_USERNAME") : project.findProperty("vstsUsername")
                password System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") != null ? System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") : project.findProperty("vstsMavenAccessToken")
            }
        }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.kotlinVersion}"
        classpath "com.android.tools.build:gradle:$rootProject.ext.gradleVersion"
    }
}

allprojects {
    repositories {
        // If you don't have access to the package feed uncomment these repositories
        // mavenCentral()
        google()
        mavenLocal()
        maven {
            name "vsts-maven-new-android"
            url "https://identitydivision.pkgs.visualstudio.com/_packaging/NewAndroid/maven/v1"
            credentials {
                username project.vstsUsername
                password project.vstsMavenAccessToken
            }
        }
    }

    dependencyLocking {
        lockAllConfigurations()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
