pluginManagement {
     // Note: Since our plugin references the android plugin we need to include google() here.
     repositories {
         // If you don't have access to the package feed uncomment these repositories
         //  mavenCentral()
         google()
         gradlePluginPortal()
         maven {
             name "vsts-maven-new-android"
             url "https://identitydivision.pkgs.visualstudio.com/_packaging/NewAndroid/maven/v1"
             credentials {
                 username System.getenv("ENV_VSTS_MVN_CRED_USERNAME") != null ? System.getenv("ENV_VSTS_MVN_CRED_USERNAME") : settings.ext.find("vstsUsername")
                 password System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") != null ? System.getenv("ENV_VSTS_MVN_CRED_ACCESSTOKEN") : settings.ext.find("vstsMavenAccessToken")
             }
         }
     }
 }
include ':msal', ':common', ':keyvault', ':labapi', ':testutils', ':pop-benchmarker',
        ':package-inspector', ':msalautomationapp', ':uiautomationutilities', ':common4j',
        ':LabApiUtilities'

project(':common').projectDir = new File('common/common')
project(':keyvault').projectDir = new File('common/keyvault')
project(':labapi').projectDir = new File('common/labapi')
project(':testutils').projectDir = new File('common/testutils')
project(':uiautomationutilities').projectDir = new File('common/uiautomationutilities')
project(':common4j').projectDir = new File('common/common4j')
project(':LabApiUtilities').projectDir = new File('common/LabApiUtilities')

// test apps
include ':testapps:sample'
include ':testapps:testapp'
include ':testapps:automationapp'
