# File: credscan-policheck.yml

parameters:
- name: policheckCmdLineArgsDir

steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: Run CredScan
  inputs:
    toolMajorVersion: V2
    debugMode: false
    folderSuppression: false
- task: PoliCheck@1
  name: PoliCheck_2
  displayName: Run PoliCheck
  inputs:
    inputType: Basic
    cmdLineArgs: /F:$(Build.SourcesDirectory)+"\${{ parameters.policheckCmdLineArgsDir }}\src\" /T:9 /O:\"PoliCheck.xml\"
    importEx: 0
    optionsFC: 1
    optionsXS: 1
    optionsSEV: 1|2
    optionsPE: 1|2|3|4
- task: PublishSecurityAnalysisLogs@2
  name: PublishSecurityAnalysisLogs15
  displayName: Publish Security Analysis Logs

