gcloud:
  type: instrumentation

flank:
  ## Max Test Shards
  # test shards - the amount of groups to split the test suite into
  # set to -1 to use one shard per test. default: 1
   max-test-shards: 1

  ## Shard Time
  # shard time - the amount of time tests within a shard should take
  # when set to > 0, the shard count is dynamically set based on time up to the maximum limit defined by max-test-shards
  # 2 minutes (120) is recommended.
  # default: -1 (unlimited)
   shard-time: -1

  ## Number of Test Runs
  # test runs - the amount of times to run the tests.
  # 1 runs the tests once. 10 runs all the tests 10x
   num-test-runs: 1

  ## Smart Flank GCS Path
  # Google cloud storage path where the JUnit XML results from the last run is stored.
   smart-flank-gcs-path: gs://tmp_flank/tmp/JUnitReport.xml

  ## Smart Flank Upload Disable flag
  # Disables smart flank JUnit XML uploading. Useful for preventing timing data from being updated.
  # Default: false
   smart-flank-disable-upload: false

  ## Use Average Test Time for New Tests flag
  # Enable using average time from previous tests duration when using SmartShard and tests did not run before.
  # Default: false
   use-average-test-time-for-new-tests: true

  ## Default Test Time
  # Set default test time used for calculating shards.
  # Default: 120.0
   default-test-time: 15

  ## Default Class Test Time
  # Set default test time (in seconds) used for calculating shards of parametrized classes when previous tests results are not available.
  # Default test time for classes should be different from the default time for test
  # Default: 240.0
   default-class-test-time: 30

  ## Disable Sharding flag
  # Disables sharding. Useful for parameterized tests.
   disable-sharding: false

  ## Test Targets Always Run
  # always run - these tests are inserted at the beginning of every shard
  # Execution order is not guaranteed by Flank. Users are responsible for configuring their own device test runner logic.
   test-targets-always-run:
     - class com.example.app.ExampleUiTest#testPasses

  ## Files to Download
  # regex is matched against bucket paths, for example: 2019-01-09_00:13:06.106000_YCKl/shard_0/NexusLowRes-28-en-portrait/bugreport.txt
   files-to-download:
     - .*\.mp4$

  ## Billing Project ID
  # The billing enabled Google Cloud Platform project id to use
   project: flank-open-source

  ## Local Results Directory
  # Local folder to store the test result. Folder is DELETED before each run to ensure only artifacts from the new run are saved.
   local-result-dir: flank

  ## Keep File Path flag
  # Keeps the full path of downloaded files. Required when file names are not unique.
  # Default: false
   keep-file-path: false

  ## Additional App/Test APKS
  # Include additional app/test apk pairs in the run. Apks are unique by just filename and not by path!
  # If app is omitted, then the top level app is used for that pair.
  # You can overwrite global config per each test pair.
  # Currently supported options are: max-test-shards, test-targets, client-details, environment-variables, device
   additional-app-test-apks:
    - app: ../test_projects/android/apks/app-debug.apk
      test: ../test_projects/android/apks/app1-debug-androidTest.apk
      device:
        - model: Nexus6P
          version: 27
    - test: ../test_projects/android/apks/app2-debug-androidTest.apk
      max-test-shards: 5

  ## Run Timeout
  # The max time this test run can execute before it is cancelled (default: unlimited).
   run-timeout: 60m