# run MSAL with Broker UI automation testcases
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'gCloudProjectId' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
name: $(Build.BuildId)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 5 * * 1-6" # 5:00 AM UTC everyday Mon-Sat
    displayName: Daily Local MSAL UI Automation with Broker Run
    branches:
      include:
        - dev
    always: true

parameters:
  - name: firebaseDeviceId
    type: string
    displayName: Firebase Device Id
    default: blueline
    values:
      - blueline
      - flame
      - redfin
      - sailfish
      - walleye
  - name: firebaseDeviceAndroidVersion
    displayName: Firebase Device Android Version
    type: number
    default: 28
    values:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30

jobs:
  - template: ./templates/msal-broker-automation-template.yml
    parameters:
      brokerFlavor: BrokerHost
      msalFlavor: Local
      firebaseDeviceId: ${{ parameters.firebaseDeviceId }}
      firebaseDeviceAndroidVersion: ${{ parameters.firebaseDeviceAndroidVersion }}
      brokerSource: LocalApk
      resultsHistoryName: Dev MSAL with Dev BrokerHost
