# run MSAL without Broker UI automation testcases
# Variable: 'gCloudProjectId' was defined in the Variables tab
# https://dev.azure.com/IdentityDivision/Engineering/_build/index?definitionId=1743&_a=completed
name: $(Build.BuildId)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

parameters:
  - name: firebaseDeviceIdHigh
    displayName: Firebase Device Id (Api 30+)
    type: string
    default: oriole
  - name: firebaseDeviceAndroidVersionHigh
    displayName: Firebase Device Android Version (Api 30+)
    type: number
    default: 32
  - name: firebaseDeviceIdLow
    displayName: Firebase Device Id (Api 29-)
    type: string
    default: blueline
  - name: firebaseDeviceAndroidVersionLow
    displayName: Firebase Device Android Version (Api 29-)
    type: number
    default: 28
  - name: testTargetPackages
    displayName: Packages as Test Targets
    type: string
    default: package com.microsoft.identity.client.msal.automationapp.testpass.msalonly, package com.microsoft.identity.client.msal.automationapp.testpass.b2c, notAnnotation org.junit.Ignore, notAnnotation com.microsoft.identity.client.ui.automation.annotations.DoNotRunOnPipeline

variables:
  engineeringProjectId: 'fac9d424-53d2-45c0-91b5-ef6ba7a6bf26'
  azureSamplePipelineId: 1458
  msalAutomationAppApk: msalautomationapp-local-BrokerHost-debug.apk
  msalAutomationAppTestApk: msalautomationapp-local-BrokerHost-debug-androidTest.apk
  azureSampleApk: AzureSample-local-debug.apk
  firebaseTimeout: 45m
  resultsHistoryName: Dev MSAL without Broker

stages:
  # msalautomationapp
  - stage: 'msalautomationapp'
    displayName: Build MSAL Automation APKs
    jobs:
      - template: ./templates/build-msal-automation-app.yml
        parameters:
          brokerFlavor: BrokerHost
          msalFlavor: Local
          brokerSource: LocalApk
  # Azure Sample
  - stage: 'azuresample'
    dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
    displayName: Dowload Azure Sample APK
    jobs:
      - job: 'download_azure_sample'
        displayName: Download Azure Sample
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            displayName: 'Download latest Azure Sample'
            inputs:
              buildType: 'specific'
              project: '$(engineeringProjectId)'
              definition: '$(azureSamplePipelineId)'
              artifactName: AzureSample
              itemPattern: '**/*.apk'
              targetPath: '$(Build.ArtifactStagingDirectory)/azureSample'
              buildVersionToDownload: 'latest'
          - publish: $(Build.ArtifactStagingDirectory)/azureSample
            displayName: 'Publish Azure Sample apk for later use'
            artifact: azureSample
  # MSAL without Broker Test UI stage (API 30+)
  - stage: 'msal_without_broker_high_api'
    dependsOn:
      - msalautomationapp
      - azuresample
    displayName: Running MSAL without Broker Test UI Test Suite (API 30+)
    jobs:
      - template: ./templates/run-on-firebase.yml
        parameters:
          automationAppApkPath: "$(Pipeline.Workspace)/msalautomationapks/msalautomationapp-local-BrokerHost-debug.apk"
          automationAppTestApkPath: "$(Pipeline.Workspace)/msalautomationapks/msalautomationapp-local-BrokerHost-debug-androidTest.apk"
          testTargetPackages: ${{ parameters.testTargetPackages }}
          resultsDir: "msal-BrokerHost-highapi-$(Build.BuildId)-$(Build.BuildNumber)"
          resultsHistoryName: "Dev MSAL without Broker"
          otherFiles: "/data/local/tmp/AzureSample.apk=$(Pipeline.Workspace)/azureSample/$(azureSampleApk)"
          firebaseDeviceId: ${{ parameters.firebaseDeviceIdHigh }}
          firebaseDeviceAndroidVersion: ${{ parameters.firebaseDeviceAndroidVersionHigh }}
          testRunTitle: "MSAL UI Automation - Build (API 30+) # $(Build.BuildNumber)"
          apiLevelTarget: "notAnnotation com.microsoft.identity.client.ui.automation.annotations.RunOnAPI29Minus"
  # MSAL without Broker Test UI stage (API 29-)
  - stage: 'msal_without_broker_low_api'
    dependsOn:
      - msalautomationapp
      - azuresample
    displayName: Running MSAL without Broker Test UI Test Suite (API 29-)
    jobs:
      - template: ./templates/run-on-firebase.yml
        parameters:
          automationAppApkPath: "$(Pipeline.Workspace)/msalautomationapks/msalautomationapp-local-BrokerHost-debug.apk"
          automationAppTestApkPath: "$(Pipeline.Workspace)/msalautomationapks/msalautomationapp-local-BrokerHost-debug-androidTest.apk"
          testTargetPackages: ${{ parameters.testTargetPackages }}
          resultsDir: "msal-BrokerHost-lowapi-$(Build.BuildId)-$(Build.BuildNumber)"
          resultsHistoryName: "Dev MSAL without Broker"
          otherFiles: "/data/local/tmp/AzureSample.apk=$(Pipeline.Workspace)/azureSample/$(azureSampleApk)"
          firebaseDeviceId: ${{ parameters.firebaseDeviceIdLow }}
          firebaseDeviceAndroidVersion: ${{ parameters.firebaseDeviceAndroidVersionLow }}
          testRunTitle: "MSAL UI Automation - Build (API 29-) # $(Build.BuildNumber)"
          apiLevelTarget: "annotation com.microsoft.identity.client.ui.automation.annotations.RunOnAPI29Minus"
