# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'android:serverUrl' was defined in the Variables tab
# Variable 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable 'mvnAccessToken' was defined in the Variables tab
# Variable 'test_repo_branch' was defined in the Variables tab
# Variable 'test_repo_dir' was defined in the Variables tab
variables:
- name: BuildParameters.jdkVersion
  value: 1.8
- name: BuildParameters.jdkArchitecture
  value: x64
- name: BuildParameters.javaHomeSelection
  value: JDKVersion
trigger:
  branches:
    include:
    - dev
    - master
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: pedroro/IDDP-pipelines
    endpoint: github.com_android_service_connection
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: azure-pipelines/templates/steps/credscan-policheck.yml@common
    parameters:
      policheckCmdLineArgsDir: adal
  - template: azure-pipelines/templates/steps/automation-cert.yml@common
  - task: JavaToolInstaller@0
    displayName: Use Java 8
    inputs:
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: SpotBugs@1
    inputs:
      inputType: 'guardianGlob'
      targetClassGlob: '**.jar;-|.gdn\**;'
      ruleset: 'sdlRecommemded'
      effort: 'max'
  - task: Gradle@2
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: clean msal:assembleLocal
      publishJUnitResults: false
      testResultsFiles: '**/build/test-results/TEST-*.xml'
      jdkVersion: $(BuildParameters.jdkVersion)
      jdkArchitecture: $(BuildParameters.jdkArchitecture)
      sqGradlePluginVersion: 2.0.1
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      tasks: msal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=28
      javaHomeSelection: $(BuildParameters.javaHomeSelection)
      jdkVersion: 1.11
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
