# File: azure-pipelines\pull-request-validation\pr-msal.yml
# Description: Assemble and run unit test
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
name: $(date:yyyyMMdd)$(rev:.r)
trigger: none
variables:
- name: BuildParameters.jdkVersion
  value: 1.17
- name: BuildParameters.jdkArchitecture
  value: x64
- name: BuildParameters.javaHomeSelection
  value: JDKVersion
- name: robolectricSdkVersion
  value: 33
- group: MSIDLABVARS
- group: devex-ciam-test

resources:
  repositories:
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: msal-dev
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

pool:
  name: MSSecurity-1ES-Build-Agents-Pool
  image: MSSecurity-1ES-Windows-2022
  os: windows
stages:
  - stage: build_and_test
    displayName: Build and Test
    jobs:
    - job: build_test
      displayName: PR Branch Testing
      cancelTimeoutInMinutes: 1
      variables:
        Codeql.Enabled: true
      steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - bash: |
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
        displayName: 'Set VSTS Fields in Environment'
      - template: azure-pipelines/templates/steps/automation-cert.yml@common
      - task: JavaToolInstaller@0
        displayName: Use Java 17
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: x64
          jdkSourceOption: PreInstalled
      - task: CodeQL3000Init@0
      - task: Gradle@2
        name: Gradle1
        displayName: Assemble Local
        inputs:
          tasks: clean msal:assembleLocal
          publishJUnitResults: false
          testResultsFiles: '**/build/test-results/TEST-*.xml'
          jdkVersion: $(BuildParameters.jdkVersion)
          jdkArchitecture: $(BuildParameters.jdkArchitecture)
          sqGradlePluginVersion: 2.0.1
      - task: CodeQL3000Finalize@0
      - task: Gradle@2
        displayName: Run Tests
        inputs:
          tasks: msal:jacocoTestReport  -PcodeCoverageEnabled=true -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PmockApiUrl=$(MOCK_API_URL) -PnativeAuthConfigString=$(NATIVE_AUTH_CONFIG_STRING)
          javaHomeSelection: $(BuildParameters.javaHomeSelection)
          jdkVersion: 1.17
      - publish: $(Build.SourcesDirectory)/msal/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
        artifact: jacocoReport
        displayName: 'Publish JaCoCo Report Artifact (PR Branch)'
      - task: PublishCodeCoverageResults@1
        displayName: Publish Code Coverage Results
        condition: always()
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(Build.SourcesDirectory)/msal/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml'
          reportDirectory: '$(Build.SourcesDirectory)/msal/build/reports/jacoco/jacocoTestReport/html'
          failIfCoverageEmpty: false
    - job: build_test_dev
      displayName: Dev Branch
      cancelTimeoutInMinutes: 1
      variables:
        Codeql.Enabled: true
      steps:
        - checkout: msal-dev
          clean: true
          submodules: recursive
          persistCredentials: True
        - bash: |
            echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
            echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
          displayName: 'Set VSTS Fields in Environment'
        - template: azure-pipelines/templates/steps/automation-cert.yml@common
        - task: JavaToolInstaller@0
          displayName: Use Java 17
          inputs:
            versionSpec: '17'
            jdkArchitectureOption: x64
            jdkSourceOption: PreInstalled
        - task: CodeQL3000Init@0
        - task: Gradle@2
          name: Gradle1
          displayName: Assemble Local
          inputs:
            tasks: clean msal:assembleLocal
            publishJUnitResults: false
            testResultsFiles: '**/build/test-results/TEST-*.xml'
            jdkVersion: $(BuildParameters.jdkVersion)
            jdkArchitecture: $(BuildParameters.jdkArchitecture)
            sqGradlePluginVersion: 2.0.1
        - task: CodeQL3000Finalize@0
        - task: Gradle@2
          displayName: Run Tests
          inputs:
            tasks: msal:jacocoTestReport  -PcodeCoverageEnabled=true -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PmockApiUrl=$(MOCK_API_URL) -PnativeAuthConfigString=$(NATIVE_AUTH_CONFIG_STRING)
            javaHomeSelection: $(BuildParameters.javaHomeSelection)
            jdkVersion: 1.17
        - publish: $(Build.SourcesDirectory)/msal/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          artifact: jacocoReportDev
          displayName: 'Publish JaCoCo Report Artifact (Dev Branch)'
    - job: spotbugs
      displayName: SpotBugs (PR)
      cancelTimeoutInMinutes: 1
      steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - bash: |
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
        displayName: 'Set VSTS Fields in Environment'
      - template: azure-pipelines/templates/steps/spotbugs.yml@common
        parameters:
          project: msal
    - job: lint
      displayName: Lint (PR)
      cancelTimeoutInMinutes: 1
      steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: True
      - bash: |
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
          echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
        displayName: 'Set VSTS Fields in Environment'
      - task: Gradle@3
        displayName: Lint Local debug
        inputs:
          tasks: clean msal:lintLocalDebug
          publishJUnitResults: false
          jdkVersion: 1.17
  - template: azure-pipelines/code-coverage/compare-code-coverage.yml@common
...
