name: Code coverage

on:
  pull_request:

env:
  ROBOELECTRIC_SDK_VERSION: 28

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Install Automation Cert
        shell: pwsh
        run: |
          $kvSecretBytes = [System.Convert]::FromBase64String('${{secret.AndroidAutomationRunner}}')

          $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection

          $certCollection.Import($kvSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

          $protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12)

          $pfxPath = '$(Build.SourcesDirectory)' + "\TestCert.pfx"

          [System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)

          Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My

      - name: Run Coverage
        run: ./gradlew msal:localDebugMsalUnitTestCoverageReport -Plabtest -ProbolectricSdkVersion=$ROBOELECTRIC_SDK_VERSION

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ${{ github.workspace }}/msal/build/reports/jacoco/localDebugMsalUnitTestCoverageReport/localDebugMsalUnitTestCoverageReport.xml